#!/bin/sh
# -*- coding: utf-8 -*-
#
#  wifiboom.sh
#  
#  Copyright 2013 written by: TH3CR4CK3R        TOP-HAT-SEC.COM
#  Script updated to version 0.1b by: ZEROF      zerof@backbox.org
#  Date of last edit: 29/06/2013
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  
 package=$(dpkg -s macchanger|grep installed)
 echo Machanger $package
 if [ "" = "$package" ]; then
      echo "No MAC. Setting up macchanger"
      sudo apt-get --force-yes --yes install macchanger
  sleep 1    
 fi
  package1=$(dpkg -s toilet|grep installed)
 echo Toilet $package1
 if [ "" = "$package1" ]; then
      echo "No toilet. Setting up toilet"
      sudo apt-get --force-yes --yes install toilet
 fi
sleep 1   
clear
GREEN='\033[01;32m'
WHITE='\033[01;37m'
STRING="WIFIBOOM"
tput setaf 2 t && toilet -f pagga $(echo "\033[8C $STRING \033[7C");
printf "\033[m"
echo ""
echo $WHITE "#################################################################"
echo " #################################################################"
echo " ##   THIS SCRIPT WILL PUT THE INTERFACE THAT YOU CHOOSE INTO   ##"
echo " ##  MONITOR MODE. IT WILL THEN FAKE THE MAC FOR BOTH MONITOR   ##"
echo " ##                  MODE AND MANAGED MODE                      ##"
echo " ##      00:11:22:33:44:55 IS THE DEFAULT MAC ADDRESS USED      ##"
echo " #################################################################"
echo " #################################################################"
echo ""
echo "     --------------------------------------------------------"
echo "     -----MAKE SURE THAT YOUR WIRELESS CARD IS CONNECTED-----"
echo "     --------------------------------------------------------"
echo ""
echo "          **********************************************"
echo "          ******PRESS ENTER WHEN READY TO CONTINUE******"
echo "          **********************************************"
printf "\033[m"
echo
read enter
sleep 0.5
clear
echo
airmon-ng
echo
echo "  WHICH INTERFACE WOULD YOU LIKE TO USE? \c" 
read IFACE
sleep 0.25 
clear
echo ""
echo ""
echo $WHITE "###########################################################"
echo " ###########################################################"
echo " ##                                                       ##"
echo " ##       BOOSTING TXPOWER from 20 > 30 on $IFACE          ##"
echo " ##                                                       ##"
echo " ###########################################################"
echo " ###########################################################"
printf "\033[m"
sleep 1
echo ""
iw reg set BO
sleep 1
echo ""
iwconfig $IFACE txpower 30
echo ""
sleep 1
clear
echo ""
echo ""
echo $WHITE "##########################################################"
echo " ################ PLEASE SELECT AN OPTION #################"
echo " ##########################################################"
echo " "
echo "  OPTION 1 - USE DEFAULT MAC ADDRESS"
echo ""
echo "  OPTION 2 - USE CUSTOM MAC ADDRESS"
echo "" 
echo "  ENTER YOUR CHOICE [1/2]: \c"
read option



if [ $option =  "2" ]; then

  echo
  echo ""
  echo "  WHAT MAC ADDRESS WOULD YOU LIKE TO USE: \c"
  read MMAC
  sleep 0.75
  clear
  echo ""
  echo ""
  echo $WHITE "#############################################################"
  echo " #############################################################"
  echo " ##                                                         ##"
  echo " ##   BRINGING DOWN $IFACE TO CHANGE THE MAC ADDRESS         ##"
  echo " ##      ====SETTING TO: $MMAC                  ##"
  echo " #############################################################"
  echo " #############################################################"
  printf "\033[m"
  sleep 2
  echo 
  ifconfig $IFACE down
  sleep 0.25 
  macchanger -m $MMAC $IFACE
  sleep 0.25
  clear
  echo ""
  echo "" 
  echo $WHITE "##############################################################"
  echo " ##############################################################"
  echo " ##                                                          ##"
  echo " ##       BRINGING UP $IFACE..... THIS MAY TAKE A MOMENT      ##"
  echo " ##                                                          ##"
  echo " ##############################################################"
  echo " ##############################################################"
  printf "\033[m"
  sleep 0.5
  ifconfig $IFACE up
  sleep 0.5
  clear
  echo ""
  echo ""
  echo $WHITE "##############################################################"
  echo " ##############################################################"
  echo " ##                                                          ##"
  echo " ##             PUTTING $IFACE INTO MONITOR MODE              ##"
  echo " ##                                                          ##"
  echo " ##############################################################"
  echo " ##############################################################"
  printf "\033[m"
  sleep 1.5
  airmon-ng start $IFACE
  sleep 0.5
  clear
  echo ""
  echo ""
  echo $WHITE "##############################################################"
  echo " ##############################################################"
  echo " ##                                                          ##"
  echo " ##    NOW BRINGING DOWN Mon0 & AND CHANGING THE MAC ADDRESS ##"
  echo " ##    ----CHANGING TO: $MMAC                    ##"
  echo " ##############################################################"
  echo " ##############################################################"
  printf "\033[m"
  echo ""
  echo ""
  sleep 0.5
  ifconfig mon0 down
  sleep 0.5
  echo ""
  macchanger -m $MMAC mon0
  sleep 0.25
  echo ""
  ifconfig mon0 up
  sleep 0.5
  clear
  echo ""
  echo ""
  echo $WHITE"##############################################################"
  echo " ##############################################################"
  echo " ##  $IFACE HAS BEEN PUT INTO MONITOR MODE                    ##"
  echo " ##  THE TXPOWER HAS BEEN SET TO:30                          ##"
  echo " ##  THE MAC ADDRESS OF BOTH $IFACE AND MON0                  ##"
  echo " ##  HAVE BEEN SPOOFED TO: $MMAC                 ##"
  echo " ##############################################################"
  echo " ##############################################################"
  printf "\033[m"
  echo ""
  echo ""
  echo " PRESS ENTER TO START HACKING: \c"
  read ENTER
  sleep 0.5
  exit
  
  
else
if [ $option = "1" ]; then

clear
  echo ""
  echo ""
  echo $WHITE "#############################################################"
  echo " #############################################################"
  echo " ##                                                         ##"
  echo " ##   BRINGING DOWN $IFACE TO CHANGE THE MAC ADDRESS         ##"
  echo " ##      ====SETTING TO: 00:11:22:33:44:55                  ##"
  echo " #############################################################"
  echo " #############################################################"
  sleep 0.5
  echo 
  ifconfig $IFACE down
  sleep 0.25 
  echo
  macchanger -m 00:11:22:33:44:55 $IFACE
  sleep 0.25
  clear
  echo ""
  echo "" 
  echo $WHITE "##############################################################"
  echo " ##############################################################"
  echo " ##                                                          ##"
  echo " ##       BRINGING UP $IFACE..... THIS MAY TAKE A MOMENT      ##"
  echo " ##                                                          ##"
  echo " ##############################################################"
  echo " ##############################################################"
  printf "\033[m"
  sleep 0.5
  echo
  ifconfig $IFACE up
  sleep 0.5
  clear
  echo ""
  echo ""
  echo $WHITE "##############################################################"
  echo " ##############################################################"
  echo " ##                                                          ##"
  echo " ##            PUTTING $IFACE INTO MONITOR MODE               ##"
  echo " ##                                                          ##"
  echo " ##############################################################"
  echo " ##############################################################"
  printf "\033[m"
  sleep 0.5
  airmon-ng check killall
  airmon-ng start $IFACE
  sleep 0.5
  clear
  echo ""
  echo ""
  echo $WHITE "##############################################################"
  echo " ##############################################################"
  echo " ##                                                          ##"
  echo " ##    NOW BRINGING DOWN Mon0 & AND CHANGING THE MAC ADDRESS ##"
  echo " ##    ----CHANGING TO: 00:11:22:33:44:55                    ##"
  echo " ##############################################################"
  echo " ##############################################################"
  printf "\033[m"
  sleep 0.5
  ifconfig mon0 down
  sleep 0.5
  echo
  macchanger -m 00:11:22:33:44:55 mon0
  echo
  sleep 0.25
  ifconfig mon0 up
  sleep 0.5
  echo 
  sleep 1
  clear
  echo ""
  echo ""
  echo $WHITE "##############################################################"
  echo " ##############################################################"
  echo " ##  $IFACE HAS BEEN PUT INTO MONITOR MODE                    ##"
  echo " ##  THE TXPOWER HAS BEEN SET TO:30                          ##"
  echo " ##  THE MAC ADDRESS OF BOTH $IFACE AND mon0                  ##"
  echo " ##  HAVE BEEN SPOOFED TO: 00:11:22:33:44:55                 ##"
  echo " ##############################################################"
  echo " ##############################################################"
  printf "\033[m"
  echo ""
  echo ""
  echo " PRESS ENTER TO START HACKING: \c"
  read ENTER
  sleep 0.5
  airodump-ng mon0
  exit
fi
fi
